# Generated by Django 5.0.7 on 2024-07-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='days',
        ),
    ]
