# Generated by Django 5.0.7 on 2024-07-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_packages_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='depart_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='destination',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='duration',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='return_time',
            field=models.DateField(auto_now=True),
        ),
    ]
