# Generated by Django 5.0.7 on 2024-07-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_packages_depart_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='depart_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='packages',
            name='return_time',
            field=models.DateField(),
        ),
    ]
